<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Asura.Application\Asura.Application.csproj" />
    <ProjectReference Include="..\Asura.Core\Asura.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Porta.Pty" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <AsuraPtyRid Condition="'$(RuntimeIdentifier)' != ''">$(RuntimeIdentifier)</AsuraPtyRid>
    <AsuraPtyRid Condition="'$(RuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</AsuraPtyRid>
    <AsuraPtyLibrary Condition="$(AsuraPtyRid.StartsWith('osx-'))">libasura_pty.dylib</AsuraPtyLibrary>
    <AsuraPtyLibrary Condition="$(AsuraPtyRid.StartsWith('linux-'))">libasura_pty.so</AsuraPtyLibrary>
  </PropertyGroup>
  <ItemGroup Condition="'$(AsuraPtyLibrary)' != ''">
    <Content Include="../../native/artifacts/$(AsuraPtyRid)/$(AsuraPtyLibrary)" Link="$(AsuraPtyLibrary)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" Condition="Exists('../../native/artifacts/$(AsuraPtyRid)/$(AsuraPtyLibrary)')" />
  </ItemGroup>

</Project>
