namespace Asura.Files;

public enum FileProviderErrorCode
{
    UnsupportedCapability,
    InvalidLocation,
    InvalidName,
    OutsideRoot,
    RootMutationNotAllowed,
    NotFound,
    AlreadyExists,
    Conflict,
    PreconditionFailed,
    RangeNotSatisfiable,
    LimitExceeded,
    AccessDenied,
    HostKeyUnknown,
    HostKeyChanged,
    HostKeyStoreInvalid,
    NotDirectory,
    IsDirectory,
    DirectoryNotEmpty,
    LinkNotAllowed,
    SharingViolation,
    QuotaExceeded,
    UnexpectedEndOfStream,
    PartialTransfer,
    Cancelled,
    IoFailure,
    AuthenticationRequired,
}
