<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GhostShell.Application\GhostShell.Application.csproj" />
    <ProjectReference Include="..\GhostShell.Core\GhostShell.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Porta.Pty" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <GhostShellPtyRid Condition="'$(RuntimeIdentifier)' != ''">$(RuntimeIdentifier)</GhostShellPtyRid>
    <GhostShellPtyRid Condition="'$(RuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</GhostShellPtyRid>
    <GhostShellPtyLibrary Condition="$(GhostShellPtyRid.StartsWith('osx-'))">libghostshell_pty.dylib</GhostShellPtyLibrary>
    <GhostShellPtyLibrary Condition="$(GhostShellPtyRid.StartsWith('linux-'))">libghostshell_pty.so</GhostShellPtyLibrary>
  </PropertyGroup>
  <ItemGroup Condition="'$(GhostShellPtyLibrary)' != ''">
    <Content Include="../../native/artifacts/$(GhostShellPtyRid)/$(GhostShellPtyLibrary)" Link="$(GhostShellPtyLibrary)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" Condition="Exists('../../native/artifacts/$(GhostShellPtyRid)/$(GhostShellPtyLibrary)')" />
  </ItemGroup>

</Project>
