<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GhostShell.Application\GhostShell.Application.csproj" />
    <ProjectReference Include="..\GhostShell.Core\GhostShell.Core.csproj" />
    <ProjectReference Include="..\GhostShell.Databases\GhostShell.Databases.csproj" />
    <ProjectReference Include="..\GhostShell.Files\GhostShell.Files.csproj" />
    <ProjectReference Include="..\GhostShell.Infrastructure\GhostShell.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GhostShell" />
    <InternalsVisibleTo Include="GhostShell.Backend" />
    <InternalsVisibleTo Include="GhostShell.Architecture.Tests" />
  </ItemGroup>

</Project>
