using System.IO.Compression;
using Asura.Application;
using Asura.Previews;
using SharpCompress.Common;
using SharpCompress.Writers.Zip;

namespace Asura.Previews.Tests;

public sealed class ArchivePagingTests
{
    [Fact]
    public void Uncached_adapter_uses_the_unmodified_package()
    {
        // The old source fork added this public method. Keep the compatibility
        // test from accidentally passing against a stale fork in build output.
        Assert.Null(typeof(SharpCompress.Archives.Zip.ZipArchive).GetMethod("EnumerateEntriesUncached"));
        Assert.Equal(new Version(0, 50, 3, 0), typeof(SharpCompress.Archives.Zip.ZipArchive).Assembly.GetName().Version);
    }

    [Fact]
    public async Task First_and_deep_pages_keep_only_requested_rows_and_do_not_read_bodies()
    {
        var bytes = CreateManyEntries(20_000);
        using var content = new InstrumentedContent(bytes);
        var reader = new ArchiveTableOfContents();
        var first = await reader.ReadAsync(content, "many.zip", 8, CancellationToken.None);
        Assert.Equal(8, first!.Count);
        Assert.True(content.LastStream!.BytesRead < 100_000);
        Assert.True(content.LastStream.Disposed);
        var later = await reader.ReadAsync(content, "many.zip", 8, CancellationToken.None, 19_990);
        Assert.Equal(8, later!.Count);
        Assert.Equal("entry-19989", later[0].Path);
        Assert.True(content.LastStream!.Disposed);
        var repeat = await reader.ReadAsync(content, "many.zip", 8, CancellationToken.None, 19_990);
        Assert.Equal(later, repeat);
    }

    [Fact]
    public void Uncached_traversal_does_not_retain_skipped_headers()
    {
        using var stream = new MemoryStream(CreateManyEntries(20_000), writable: false);
        using var archive = (SharpCompress.Archives.Zip.ZipArchive)SharpCompress.Archives.Zip.ZipArchive.OpenArchive(stream);
        var probes = CaptureWeakReferences(archive);
        GC.Collect();
        GC.WaitForPendingFinalizers();
        GC.Collect();
        Assert.All(probes, probe => Assert.False(probe.IsAlive));
        // The archive stays alive: collection is not merely disposal freeing a cache.
        GC.KeepAlive(archive);
    }

    private static List<WeakReference> CaptureWeakReferences(SharpCompress.Archives.Zip.ZipArchive archive)
    {
        var probes = new List<WeakReference>();
        var index = 0;
        foreach (var entry in archive.EnumerateEntriesUncached())
        {
            if (index++ % 1000 == 0)
            {
                probes.Add(new WeakReference(entry));
            }
        }
        return probes;
    }

    [Fact]
    public async Task Zip64_and_long_names_are_listed_without_extracting()
    {
        using var bytes = new MemoryStream();
        var name = new string('x', 20_000);
        using (var writer = new ZipWriter(bytes, new ZipWriterOptions(CompressionType.None) { UseZip64 = true }))
        using (var body = new MemoryStream("contents"u8.ToArray()))
        {
            writer.Write(name, body, modificationTime: null);
        }
        using var content = new InstrumentedContent(bytes.ToArray(), guardBody: false);
        var result = await new ArchiveTableOfContents().ReadAsync(content, "zip64.zip", 1, CancellationToken.None);
        Assert.Equal(name, Assert.Single(result!).Path);
    }

    [Fact]
    public async Task Encrypted_descriptor_entry_metadata_does_not_need_a_password()
    {
        // Generated by zip -P fixture-only; payload is synthetic, password is not used by the reader.
        var bytes = Convert.FromBase64String("UEsDBBQACQAIAEMCKl0AAEMCAAAAACQAAAAVABwAYXN1cmEtemlwLWZpeHR1cmUudHh0VVQJAAMNzaFqDc2hanV4CwABBPYBAAAEFAAAAAWt62a2hgrN/cqRhDrDKHRW/B4E6EGi3sWVzX3iMm9/X5jgvV/txL2cFnPN7SZAUJOpUEsHCC2H9r4yAAAAJAAAAFBLAQIeAxQACQAIAEMCKl0th/a+MgAAACQAAAAVABgAAAAAAAEAAACkgQAAAABhc3VyYS16aXAtZml4dHVyZS50eHRVVAUAAw3NoWp1eAsAAQT2AQAABBQAAABQSwUGAAAAAAEAAQBbAAAAkQAAAAAA");
        using var content = new InstrumentedContent(bytes, guardBody: false);
        var result = await new ArchiveTableOfContents().ReadAsync(content, "encrypted.zip", 1, CancellationToken.None);
        var entry = Assert.Single(result!);
        Assert.Equal("asura-zip-fixture.txt", entry.Path);
        Assert.Equal(36, entry.Size);
    }

    [Fact]
    public async Task Cancellation_during_traversal_disposes_the_stream()
    {
        using var cancellation = new CancellationTokenSource();
        using var content = new InstrumentedContent(CreateManyEntries(2000), onRead: () => cancellation.Cancel());
        await Assert.ThrowsAnyAsync<OperationCanceledException>(async () =>
            await new ArchiveTableOfContents().ReadAsync(content, "cancel.zip", 1000, cancellation.Token));
        Assert.True(content.LastStream!.Disposed);
    }

    private static byte[] CreateManyEntries(int count)
    {
        using var result = new MemoryStream();
        using (var writer = new ZipArchive(result, ZipArchiveMode.Create, leaveOpen: true))
        {
            using (var body = writer.CreateEntry("body", CompressionLevel.NoCompression).Open())
            {
                body.Write(new byte[256 * 1024]);
            }
            for (var index = 0; index < count; index++)
            {
                writer.CreateEntry($"entry-{index}");
            }
        }
        return result.ToArray();
    }

    private sealed class InstrumentedContent(byte[] bytes, bool guardBody = true, Action? onRead = null) : FilePreviewContent
    {
        public ProbeStream? LastStream { get; private set; }
        public override long Length => bytes.Length;
        public override Stream OpenRead() => LastStream = new ProbeStream(bytes, guardBody, onRead);
    }

    private sealed class ProbeStream(byte[] bytes, bool guardBody, Action? onRead) : MemoryStream(bytes, 0, bytes.Length, writable: false, publiclyVisible: true)
    {
        public bool Disposed { get; private set; }
        public long BytesRead { get; private set; }
        public override int Read(byte[] buffer, int offset, int count) => Read(buffer.AsSpan(offset, count));
        public override int Read(Span<byte> buffer)
        {
            // Initial format sniffing and the final EOCD search are allowed;
            // body contents well between them must never be consulted.
            if (guardBody && Position >= 1024 && Position < 256 * 1024)
            {
                throw new InvalidOperationException("Archive listing read entry body data.");
            }
            onRead?.Invoke();
            var read = Math.Min(buffer.Length, checked((int)(Length - Position)));
            GetBuffer().AsSpan(checked((int)Position), read).CopyTo(buffer);
            Position += read;
            BytesRead += read;
            return read;
        }
        protected override void Dispose(bool disposing)
        {
            Disposed = true;
            base.Dispose(disposing);
        }
    }
}
