using Asura.Application;

namespace Asura.Databases.IntegrationTests;

internal static class OracleFirebirdProviderCases
{
    private const string Password = "Asura_Test1!";

    public static DatabaseProviderCase Oracle { get; } = new ContainerDatabaseProviderCase(
        "oracle",
        "Oracle Database Free 23.26.2",
        "container-registry.oracle.com/database/free:23.26.2.0-lite",
        1521,
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["ORACLE_PWD"] = Password,
        },
        [],
        static (host, port) =>
            $"Data Source={host}:{port}/FREEPDB1;User Id=SYSTEM;Password={Password};Pooling=false;Connection Timeout=15",
        "SELECT 1 FROM DUAL",
        CreateOracleSeed(),
        new DatabaseProviderExpectations(
            CanEdit: true,
            HasIndexes: true,
            HasIdentity: true,
            HasGeneratedColumn: true,
            RequiredValueKinds: new HashSet<DatabaseValueKind>
            {
                DatabaseValueKind.Text,
                DatabaseValueKind.Decimal,
                DatabaseValueKind.Boolean,
                DatabaseValueKind.TimestampWithZone,
                DatabaseValueKind.Binary,
            },
            ExpectedCodeLength: 80,
            ExpectedScorePrecision: 12,
            ExpectedScoreScale: 2,
            ScoreIndex: new DatabaseIndexExpectations(
                FirstColumnDescending: false)));

    public static DatabaseProviderCase Firebird { get; } = new ContainerDatabaseProviderCase(
        "firebird",
        "Firebird 5.0.4",
        "firebirdsql/firebird:5.0.4-trixie",
        3050,
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["FIREBIRD_ROOT_PASSWORD"] = Password,
            ["FIREBIRD_DATABASE"] = "asura.fdb",
            ["FIREBIRD_DATABASE_DEFAULT_CHARSET"] = "UTF8",
        },
        [],
        static (host, port) =>
            $"DataSource={host};Port={port};Database=/var/lib/firebird/data/asura.fdb;User=SYSDBA;Password={Password};Charset=UTF8;Dialect=3;Pooling=false;Connection Timeout=15",
        "SELECT 1 FROM RDB$DATABASE",
        CreateFirebirdSeed(),
        new DatabaseProviderExpectations(
            CanEdit: true,
            HasIndexes: true,
            HasIdentity: true,
            HasGeneratedColumn: true,
            RequiredValueKinds: new HashSet<DatabaseValueKind>
            {
                DatabaseValueKind.SignedInteger,
                DatabaseValueKind.Text,
                DatabaseValueKind.Decimal,
                DatabaseValueKind.Boolean,
                DatabaseValueKind.Timestamp,
                DatabaseValueKind.Binary,
            },
            ExpectedCodeLength: 80,
            ExpectedScorePrecision: 12,
            ExpectedScoreScale: 2,
            ScoreIndex: new DatabaseIndexExpectations(
                FirstColumnDescending: true)));

    private static DatabaseSeed CreateOracleSeed() => new(
        [
            """
            CREATE OR REPLACE FUNCTION "viewer_identity"("value" NUMBER)
            RETURN NUMBER
            IS
            BEGIN
                RETURN "value";
            END;
            """,
            """
            CREATE TABLE "viewer_rows" (
                "id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "code" VARCHAR2(80 CHAR) NOT NULL UNIQUE,
                "title" VARCHAR2(200 CHAR) NOT NULL,
                "score" NUMBER(12, 2) NOT NULL,
                "enabled" BOOLEAN NOT NULL,
                "note" VARCHAR2(1000 CHAR) NULL,
                "status" VARCHAR2(40 CHAR) DEFAULT 'draft' NOT NULL,
                "created_at" TIMESTAMP WITH TIME ZONE
                    DEFAULT TO_TIMESTAMP_TZ(
                        '2025-01-01 00:00:00 +00:00',
                        'YYYY-MM-DD HH24:MI:SS TZH:TZM') NOT NULL,
                "payload" CLOB DEFAULT '{}' NOT NULL,
                "blob_value" RAW(32) NULL,
                "computed_label" VARCHAR2(281 CHAR)
                    GENERATED ALWAYS AS ("title" || ':' || "code") VIRTUAL,
                CONSTRAINT "ck_viewer_rows_payload_json" CHECK ("payload" IS JSON)
            )
            """,
            "CREATE INDEX \"idx_viewer_rows_score\" ON \"viewer_rows\" (\"score\", \"title\")",
            """
            INSERT INTO "viewer_rows"
                ("code", "title", "score", "enabled", "note", "status", "created_at", "payload", "blob_value")
            VALUES
                ('alpha', 'Alpha', -100.00, TRUE, 'one', DEFAULT,
                 TO_TIMESTAMP_TZ('2025-01-01 00:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
                 '{"slot":1}', HEXTORAW('0102'))
            """,
            """
            INSERT INTO "viewer_rows"
                ("code", "title", "score", "enabled", "note", "status", "created_at", "payload", "blob_value")
            VALUES
                ('beta', 'Beta', 0.00, FALSE, 'Robert''); DROP TABLE viewer_rows;--', 'published',
                 TO_TIMESTAMP_TZ('2025-01-02 00:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
                 '{"slot":2}', NULL)
            """,
            """
            INSERT INTO "viewer_rows"
                ("code", "title", "score", "enabled", "note", "created_at", "payload")
            VALUES
                ('literal', 'literal%_!needle', 100.00, TRUE, NULL,
                 TO_TIMESTAMP_TZ('2025-01-03 00:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
                 '{"slot":3}')
            """,
            """
            INSERT INTO "viewer_rows"
                ("code", "title", "score", "enabled", "note", "created_at", "payload")
            VALUES
                ('omega-a', 'Omega', 300.00, TRUE, 'four',
                 TO_TIMESTAMP_TZ('2025-01-04 00:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
                 '{"slot":4}')
            """,
            """
            INSERT INTO "viewer_rows"
                ("code", "title", "score", "enabled", "note", "created_at", "payload")
            VALUES
                ('omega-b', 'unicode-🧪', 300.00, FALSE, 'comma,"quote"',
                 TO_TIMESTAMP_TZ('2025-01-05 00:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
                 '{"slot":5}')
            """,
            """
            INSERT INTO "viewer_rows" ("code", "title", "score", "enabled", "note")
            SELECT 'row-' || TO_CHAR(value, 'FM000'),
                   'Row ' || TO_CHAR(value),
                   1000 + value,
                   CASE WHEN MOD(value, 2) = 0 THEN TRUE ELSE FALSE END,
                   CASE WHEN MOD(value, 3) = 0 THEN NULL ELSE 'filler' END
            FROM (
                SELECT LEVEL + 5 AS value
                FROM DUAL
                CONNECT BY LEVEL <= 200
            )
            """,
            "CREATE TABLE \"viewer_keyless\" (\"position\" NUMBER(19) NOT NULL, \"label\" VARCHAR2(80 CHAR) NULL)",
            """
            INSERT INTO "viewer_keyless" ("position", "label")
            SELECT value, 'keyless-' || TO_CHAR(value)
            FROM (
                SELECT LEVEL AS value
                FROM DUAL
                CONNECT BY LEVEL <= 205
            )
            """,
            "CREATE VIEW \"viewer_rows_view\" AS SELECT \"id\", \"code\", \"title\" FROM \"viewer_rows\"",
            "CREATE TABLE \"viewer odd.table\" (\"select\" NUMBER(19) NOT NULL)",
            "INSERT INTO \"viewer odd.table\" (\"select\") VALUES (42)",
        ]);

    private static DatabaseSeed CreateFirebirdSeed() => new(
        [
            """
            CREATE FUNCTION "viewer_identity"("value" BIGINT)
            RETURNS BIGINT
            AS
            BEGIN
                RETURN "value";
            END
            """,
            """
            CREATE TABLE "viewer_rows" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "code" VARCHAR(80) NOT NULL UNIQUE,
                "title" VARCHAR(200) NOT NULL,
                "score" DECIMAL(12, 2) NOT NULL,
                "enabled" BOOLEAN NOT NULL,
                "note" VARCHAR(1000),
                "status" VARCHAR(40) DEFAULT 'draft' NOT NULL,
                "created_at" TIMESTAMP DEFAULT TIMESTAMP '2025-01-01 00:00:00' NOT NULL,
                "payload" VARCHAR(1000) DEFAULT '{}' NOT NULL,
                "blob_value" BLOB SUB_TYPE BINARY,
                "computed_label" VARCHAR(281)
                    COMPUTED BY ("title" || ':' || "code")
            )
            """,
            "CREATE DESCENDING INDEX \"idx_viewer_rows_score\" ON \"viewer_rows\" (\"score\", \"title\")",
            """
            INSERT INTO "viewer_rows"
                ("code", "title", "score", "enabled", "note", "status", "created_at", "payload", "blob_value")
            VALUES
                ('alpha', 'Alpha', -100.00, TRUE, 'one', DEFAULT,
                 TIMESTAMP '2025-01-01 00:00:00', '{"slot":1}', X'0102')
            """,
            """
            INSERT INTO "viewer_rows"
                ("code", "title", "score", "enabled", "note", "status", "created_at", "payload", "blob_value")
            VALUES
                ('beta', 'Beta', 0.00, FALSE, 'Robert''); DROP TABLE viewer_rows;--', 'published',
                 TIMESTAMP '2025-01-02 00:00:00', '{"slot":2}', NULL)
            """,
            """
            INSERT INTO "viewer_rows"
                ("code", "title", "score", "enabled", "note", "created_at", "payload")
            VALUES
                ('literal', 'literal%_!needle', 100.00, TRUE, NULL,
                 TIMESTAMP '2025-01-03 00:00:00', '{"slot":3}')
            """,
            """
            INSERT INTO "viewer_rows"
                ("code", "title", "score", "enabled", "note", "created_at", "payload")
            VALUES
                ('omega-a', 'Omega', 300.00, TRUE, 'four',
                 TIMESTAMP '2025-01-04 00:00:00', '{"slot":4}')
            """,
            """
            INSERT INTO "viewer_rows"
                ("code", "title", "score", "enabled", "note", "created_at", "payload")
            VALUES
                ('omega-b', 'unicode-🧪', 300.00, FALSE, 'comma,"quote"',
                 TIMESTAMP '2025-01-05 00:00:00', '{"slot":5}')
            """,
            """
            EXECUTE BLOCK AS
                DECLARE row_value INTEGER = 6;
            BEGIN
                WHILE (row_value <= 205) DO
                BEGIN
                    INSERT INTO "viewer_rows"
                        ("code", "title", "score", "enabled", "note")
                    VALUES
                        ('row-' || LPAD(CAST(:row_value AS VARCHAR(3)), 3, '0'),
                         'Row ' || CAST(:row_value AS VARCHAR(10)),
                         1000 + :row_value,
                         MOD(:row_value, 2) = 0,
                         IIF(MOD(:row_value, 3) = 0, NULL, 'filler'));
                    row_value = row_value + 1;
                END
            END
            """,
            "CREATE TABLE \"viewer_keyless\" (\"position\" BIGINT NOT NULL, \"label\" VARCHAR(80))",
            """
            EXECUTE BLOCK AS
                DECLARE row_value INTEGER = 1;
            BEGIN
                WHILE (row_value <= 205) DO
                BEGIN
                    INSERT INTO "viewer_keyless" ("position", "label")
                    VALUES (:row_value, 'keyless-' || CAST(:row_value AS VARCHAR(10)));
                    row_value = row_value + 1;
                END
            END
            """,
            "CREATE VIEW \"viewer_rows_view\" AS SELECT \"id\", \"code\", \"title\" FROM \"viewer_rows\"",
            "CREATE TABLE \"viewer odd.table\" (\"select\" BIGINT NOT NULL)",
            "INSERT INTO \"viewer odd.table\" (\"select\") VALUES (42)",
        ]);
}
