using Asura.Application;

namespace Asura.Databases.IntegrationTests;

internal static class PostgreSqlProviderCases
{
    private const string Password = "Asura_Test1!";

    public static DatabaseProviderCase PostgreSql { get; } = CreatePostgreSqlCompatible(
        "postgres",
        "PostgreSQL 18.4",
        compatibilityNote: null);

    public static DatabaseProviderCase RedshiftProtocol { get; } = CreatePostgreSqlCompatible(
        "redshift",
        "Amazon Redshift protocol compatibility (PostgreSQL-backed)",
        "This exercises Asura's Redshift pgwire path only; native Redshift needs a managed AWS endpoint.");

    public static DatabaseProviderCase CockroachDb { get; } = new ContainerDatabaseProviderCase(
        "cockroach",
        "CockroachDB 26.2.4",
        "cockroachdb/cockroach:v26.2.4",
        26257,
        new Dictionary<string, string>(StringComparer.Ordinal),
        [
            "start-single-node",
            "--insecure",
            "--listen-addr=:26257",
            "--http-addr=:8080",
            "--store=type=mem,size=0.25",
        ],
        static (host, port) =>
            $"Host={host};Port={port};Database=defaultdb;Username=root;SSL Mode=Disable;Timeout=15;Command Timeout=30",
        "SELECT 1",
        CreateCockroachSeed(),
        new DatabaseProviderExpectations(
            CanEdit: true,
            HasIndexes: true,
            HasIdentity: true,
            HasGeneratedColumn: true,
            RequiredValueKinds: new HashSet<DatabaseValueKind>
            {
                DatabaseValueKind.SignedInteger,
                DatabaseValueKind.Text,
                DatabaseValueKind.Decimal,
                DatabaseValueKind.Boolean,
                DatabaseValueKind.TimestampWithZone,
                DatabaseValueKind.Binary,
                DatabaseValueKind.Json,
            },
            ExpectedScorePrecision: 12,
            ExpectedScoreScale: 2,
            ScoreIndex: new DatabaseIndexExpectations(
                FirstColumnDescending: true,
                IncludedColumn: "note")));

    private static DatabaseProviderCase CreatePostgreSqlCompatible(
        string id,
        string displayName,
        string? compatibilityNote) =>
        new ContainerDatabaseProviderCase(
            id,
            displayName,
            "postgres:18.4",
            5432,
            new Dictionary<string, string>(StringComparer.Ordinal)
            {
                ["POSTGRES_DB"] = "asura",
                ["POSTGRES_USER"] = "asura",
                ["POSTGRES_PASSWORD"] = Password,
            },
            [],
            static (host, port) =>
                $"Host={host};Port={port};Database=asura;Username=asura;Password={Password};SSL Mode=Disable;Timeout=15;Command Timeout=30",
            "SELECT 1",
            CreatePostgreSqlSeed(),
            new DatabaseProviderExpectations(
                CanEdit: !string.Equals(id, "redshift", StringComparison.Ordinal),
                HasIndexes: !string.Equals(id, "redshift", StringComparison.Ordinal),
                HasIdentity: !string.Equals(id, "redshift", StringComparison.Ordinal),
                HasGeneratedColumn: !string.Equals(id, "redshift", StringComparison.Ordinal),
                RequiredValueKinds: new HashSet<DatabaseValueKind>
                {
                    DatabaseValueKind.SignedInteger,
                    DatabaseValueKind.Text,
                    DatabaseValueKind.Decimal,
                    DatabaseValueKind.Boolean,
                    DatabaseValueKind.TimestampWithZone,
                    DatabaseValueKind.Binary,
                    DatabaseValueKind.Json,
                },
                compatibilityNote,
                ExpectedCodeLength: 80,
                ExpectedScorePrecision: 12,
                ExpectedScoreScale: 2,
                ScoreIndex: string.Equals(id, "redshift"
, StringComparison.Ordinal) ? null
                    : new DatabaseIndexExpectations(
                        FirstColumnDescending: true,
                        IncludedColumn: "note",
                        PredicateFragment: "IS NOT NULL")));

    private static DatabaseSeed CreatePostgreSqlSeed() => new(
        [
            "CREATE SCHEMA asura_extra",
            """
            CREATE FUNCTION asura_extra.viewer_identity(value BIGINT)
            RETURNS BIGINT
            LANGUAGE SQL
            IMMUTABLE
            RETURN value
            """,
            """
            CREATE TABLE "viewer_rows" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "code" VARCHAR(80) NOT NULL UNIQUE,
                "title" VARCHAR(200) NOT NULL,
                "score" NUMERIC(12, 2) NOT NULL,
                "enabled" BOOLEAN NOT NULL,
                "note" TEXT NULL,
                "status" VARCHAR(40) NOT NULL DEFAULT 'draft',
                "created_at" TIMESTAMPTZ NOT NULL DEFAULT TIMESTAMPTZ '2025-01-01 00:00:00+00',
                "payload" JSONB NOT NULL DEFAULT '{}'::jsonb,
                "blob_value" BYTEA NULL,
                "computed_label" TEXT GENERATED ALWAYS AS ("title" || ':' || "code") STORED
            )
            """,
            """
            CREATE INDEX "idx_viewer_rows_score"
            ON "viewer_rows" ("score" DESC) INCLUDE ("note")
            WHERE "note" IS NOT NULL
            """,
            """
            INSERT INTO "viewer_rows"
                ("code", "title", "score", "enabled", "note", "status", "created_at", "payload", "blob_value")
            VALUES
                ('alpha', 'Alpha', -100.00, TRUE, 'one', DEFAULT, '2025-01-01T00:00:00Z', '{"slot":1}', decode('0102', 'hex')),
                ('beta', 'Beta', 0.00, FALSE, 'Robert''); DROP TABLE viewer_rows;--', 'published', '2025-01-02T00:00:00Z', '{"slot":2}', NULL),
                ('literal', 'literal%_!needle', 100.00, TRUE, NULL, DEFAULT, '2025-01-03T00:00:00Z', '{"slot":3}', NULL),
                ('omega-a', 'Omega', 300.00, TRUE, 'four', DEFAULT, '2025-01-04T00:00:00Z', '{"slot":4}', NULL),
                ('omega-b', 'unicode-🧪', 300.00, FALSE, 'comma,"quote"', DEFAULT, '2025-01-05T00:00:00Z', '{"slot":5}', NULL)
            """,
            """
            INSERT INTO "viewer_rows" ("code", "title", "score", "enabled", "note")
            SELECT 'row-' || to_char(value, 'FM000'),
                   'Row ' || value,
                   1000 + value,
                   value % 2 = 0,
                   CASE WHEN value % 3 = 0 THEN NULL ELSE 'filler' END
            FROM generate_series(6, 205) AS value
            """,
            "CREATE TABLE \"viewer_keyless\" (\"position\" BIGINT NOT NULL, \"label\" VARCHAR(80) NULL)",
            "INSERT INTO \"viewer_keyless\" SELECT value, 'keyless-' || value FROM generate_series(1, 205) AS value",
            "CREATE VIEW \"viewer_rows_view\" AS SELECT \"id\", \"code\", \"title\" FROM \"viewer_rows\"",
            "CREATE TABLE \"viewer odd.table\" (\"select\" BIGINT NOT NULL)",
            "INSERT INTO \"viewer odd.table\" (\"select\") VALUES (42)",
        ]);

    private static DatabaseSeed CreateCockroachSeed() => new(
        [
            """
            CREATE TABLE "viewer_rows" (
                "id" INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "code" STRING NOT NULL UNIQUE,
                "title" STRING NOT NULL,
                "score" DECIMAL(12, 2) NOT NULL,
                "enabled" BOOL NOT NULL,
                "note" STRING NULL,
                "status" STRING NOT NULL DEFAULT 'draft',
                "created_at" TIMESTAMPTZ NOT NULL DEFAULT '2025-01-01 00:00:00+00',
                "payload" JSONB NOT NULL DEFAULT '{}'::jsonb,
                "blob_value" BYTES NULL,
                "computed_label" STRING AS ("title" || ':' || "code") STORED
            )
            """,
            "CREATE INDEX \"idx_viewer_rows_score\" ON \"viewer_rows\" (\"score\" DESC) STORING (\"note\")",
            """
            INSERT INTO "viewer_rows"
                ("code", "title", "score", "enabled", "note", "status", "created_at", "payload", "blob_value")
            VALUES
                ('alpha', 'Alpha', -100.00, TRUE, 'one', DEFAULT, '2025-01-01T00:00:00Z', '{"slot":1}', x'0102'),
                ('beta', 'Beta', 0.00, FALSE, 'Robert''); DROP TABLE viewer_rows;--', 'published', '2025-01-02T00:00:00Z', '{"slot":2}', NULL),
                ('literal', 'literal%_!needle', 100.00, TRUE, NULL, DEFAULT, '2025-01-03T00:00:00Z', '{"slot":3}', NULL),
                ('omega-a', 'Omega', 300.00, TRUE, 'four', DEFAULT, '2025-01-04T00:00:00Z', '{"slot":4}', NULL),
                ('omega-b', 'unicode-🧪', 300.00, FALSE, 'comma,"quote"', DEFAULT, '2025-01-05T00:00:00Z', '{"slot":5}', NULL)
            """,
            """
            INSERT INTO "viewer_rows" ("code", "title", "score", "enabled", "note")
            SELECT 'row-' || lpad(value::STRING, 3, '0'),
                   'Row ' || value,
                   1000 + value,
                   value % 2 = 0,
                   CASE WHEN value % 3 = 0 THEN NULL ELSE 'filler' END
            FROM generate_series(6, 205) AS value
            """,
            "CREATE TABLE \"viewer_keyless_source\" (\"position\" INT8 PRIMARY KEY, \"label\" STRING NULL)",
            "INSERT INTO \"viewer_keyless_source\" SELECT value, 'keyless-' || value FROM generate_series(1, 205) AS value",
            "CREATE VIEW \"viewer_keyless\" AS SELECT \"position\", \"label\" FROM \"viewer_keyless_source\"",
            "CREATE VIEW \"viewer_rows_view\" AS SELECT \"id\", \"code\", \"title\" FROM \"viewer_rows\"",
            "CREATE TABLE \"viewer odd.table\" (\"select\" INT8 NOT NULL)",
            "INSERT INTO \"viewer odd.table\" (\"select\") VALUES (42)",
        ],
        KeylessKind: DatabaseTableKind.View);
}
