<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Asura.Application\Asura.Application.csproj" />
    <ProjectReference Include="..\Asura.Core\Asura.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Asura.Mcp.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.Core" />
  </ItemGroup>

</Project>
