FROM ubuntu:24.04

ENV container=apple-container

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        bash \
        ca-certificates \
        curl \
        dbus \
        git \
        iproute2 \
        iputils-ping \
        less \
        locales \
        man-db \
        nftables \
        openconnect \
        openvpn \
        openssh-client \
        procps \
        redsocks \
        socat \
        sudo \
        systemd \
        systemd-sysv \
        tzdata \
        vim-tiny \
        wget \
        wireguard-tools \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && yes | unminimize

RUN useradd --system --no-create-home --home-dir /nonexistent \
        --shell /usr/sbin/nologin ghostshell-net

RUN : > /etc/machine-id \
    && : > /var/lib/dbus/machine-id \
    && systemctl set-default multi-user.target \
    && systemctl mask \
        dev-hugepages.mount \
        sys-fs-fuse-connections.mount \
        systemd-update-utmp.service \
        systemd-tmpfiles-setup.service \
        console-getty.service

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
