<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="LiteDB" />
    <PackageReference Include="FluentFTP" />
    <PackageReference Include="SMBLibrary" />
    <ProjectReference Include="../../vendor/sshnet/SSH.NET.csproj" />
    <PackageReference Include="SshNet.Agent" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GhostShell.Application\GhostShell.Application.csproj" />
    <ProjectReference Include="..\GhostShell.Core\GhostShell.Core.csproj" />
  </ItemGroup>

</Project>
