// Reproduce the pinned provider's resource constants without requiring PowerShell.
// Run with the repository SDK: dotnet run --file <this file> -- <resx> <output.cs>.
using System.Security.Cryptography;
using System.Text;
using System.Xml.Linq;

if (args is not [var inputPath, var outputPath])
{
    throw new ArgumentException("Expected the pinned Strings.resx path and output source path.");
}

var bytes = File.ReadAllBytes(inputPath);
var hash = Convert.ToHexStringLower(SHA256.HashData(bytes));
if (!string.Equals(hash, "f08b82f72dfbf5c8a2b1c528141145016ba5d3d31bcbb15c3e3efddc17d7631b", StringComparison.Ordinal))
{
    throw new InvalidDataException("Expected the exact SqlClient 6.0.2 Strings.resx input.");
}

using var input = new MemoryStream(bytes, writable: false);
var document = XDocument.Load(input);
var resources = document.Root?.Elements("data").ToArray()
    ?? throw new InvalidDataException("The resource document has no root.");
if (resources.Length != 1542)
{
    throw new InvalidDataException("The pinned resource count differs.");
}

var source = new StringBuilder(
    "// <auto-generated>\n" +
    "// Generated by scripts/generate-sqlclient-resource-names.cs from pinned SqlClient 6.0.2.\n" +
    "// Resource identifiers and values intentionally retain upstream spelling.\n" +
    "// </auto-generated>\n\n" +
    "using System;\n\n" +
    "namespace Microsoft.Data\n{\n" +
    "    internal partial class StringsHelper : Strings\n    {\n" +
    "        internal class ResourceNames\n        {\n");
foreach (var resource in resources)
{
    var name = resource.Attribute("name")?.Value
        ?? throw new InvalidDataException("A resource has no name.");
    var value = resource.Element("value")?.Value
        ?? throw new InvalidDataException("A resource has no value.");
    source.Append("            internal const string ").Append(name).Append(" = @\"")
        .Append(value.Replace("\"", "\"\"", StringComparison.Ordinal)).Append("\";\n");
}

source.Append("        }\n    }\n}\n");
File.WriteAllText(outputPath, source.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
