<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q8-AnyCPU" />
    <PackageReference Include="PDFtoImage" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GhostShell.Application\GhostShell.Application.csproj" />
    <ProjectReference Include="..\GhostShell.Core\GhostShell.Core.csproj" />
    <ProjectReference Include="../../vendor/sharpcompress/SharpCompress.csproj" />
  </ItemGroup>

</Project>
